// <auto-generated />
using System;
using IncidentAtlas.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IncidentAtlas.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IncidentAtlasDbContext))]
    [Migration("20260211140744_AddPublishedPostmortems")]
    partial class AddPublishedPostmortems
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("IncidentAtlas.Domain.Entities.Incident", b =>
                {
                    b.Property<Guid>("IncidentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("CreatedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<byte[]>("RowVersion")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<int>("Severity")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("IncidentId");

                    b.ToTable("Incidents", (string)null);
                });

            modelBuilder.Entity("IncidentAtlas.Domain.Entities.IncidentEvent", b =>
                {
                    b.Property<Guid>("IncidentEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Details")
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTimeOffset>("OccurredAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<int>("Sequence")
                        .HasColumnType("int");

                    b.Property<string>("Source")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("IncidentEventId");

                    b.HasIndex("IncidentId", "Sequence")
                        .IsUnique();

                    b.ToTable("IncidentEvents", (string)null);
                });

            modelBuilder.Entity("IncidentAtlas.Infrastructure.Persistence.Models.PublishedPostmortem", b =>
                {
                    b.Property<Guid>("PublishedPostmortemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CitationsJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ContentMarkdown")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("GeneratedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<Guid>("IncidentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InputEventSequenceMax")
                        .HasColumnType("int");

                    b.Property<string>("Model")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTimeOffset>("PublishedAtUtc")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("PublishedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PublishedPostmortemId");

                    b.HasIndex("IncidentId");

                    b.ToTable("PublishedPostmortems", (string)null);
                });

            modelBuilder.Entity("IncidentAtlas.Domain.Entities.IncidentEvent", b =>
                {
                    b.HasOne("IncidentAtlas.Domain.Entities.Incident", null)
                        .WithMany("Events")
                        .HasForeignKey("IncidentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IncidentAtlas.Domain.Entities.Incident", b =>
                {
                    b.Navigation("Events");
                });
#pragma warning restore 612, 618
        }
    }
}
